### ISSUE TITLE
Fails silently if unable to connect to socket

### ISSUE THREAD

**Issue by racitup** [linsomniac/python-memcached#131]
There is no indication that a socket is unreachable.

In my case the socket was owned by 'memcache:memcache' with permission 'srwx------' (the default for memcached) yet my client process was run by another user. There appears to be no indication at all that the service was unreachable. I couldn't for the life of my figure out why things weren't being cached from django.. I'm fairly new to this sort of thing.

**Comment by cactus** [comment]
Yes, python-memcached has a "fail silently" design (historical choice, that way for a long time as I recall), so that the loss of a memcache server doesn't bring your infrastructure down completely. Though, presumably, it will make it run more slowly!

There are other client libraries which will raise an error on connection failure if that is desired.

**Comment by racitup** [comment]
Sorry I don't see how this binding would "bring your infrastructure down completely" simply by logging a useful error message. I fixed it by using [pylibmc](https://github.com/lericson/pylibmc). Thanks for the response.
