### ISSUE TITLE
Performance drop between v1.53 and v1.54

### ISSUE THREAD

**Issue by edmorley** [linsomniac/python-memcached#71]
We've been using python-memcached v1.48 with Python 2.7.8 and Django 1.7.7.

I've just tried deploying python-memcached v1.54 and it increased average Memcached get response times from ~4.5ms to ~16ms, and sets from ~0.3ms to ~0.4ms (as reported by New Relic).

Before I try bisecting further, is this expected?

(If it helps, our version of `six` is 1.9.0).

**Comment by edmorley** [comment]
Bisecting...

v1.48 gets: ~4.5ms
v1.51 gets: ~3.8 ms (presumably because of https://github.com/linsomniac/python-memcached/commit/07498a0243d34562709f4b3760463dbd23db2ede)
v1.53 gets: (~same as v1.51)
v1.54 gets: ~16ms

So something in this range caused the issue:
https://github.com/linsomniac/python-memcached/compare/release-1.53...release-1.54

**Comment by edmorley** [comment]
v1.53: ~3.8ms
e346892: ~3.9ms (changes: https://github.com/linsomniac/python-memcached/compare/release-1.53...e346892)
e268a8b: ~5.2ms (changes: https://github.com/linsomniac/python-memcached/compare/e346892...e268a8b)
918e88c: ~13ms (changes: https://github.com/linsomniac/python-memcached/compare/e268a8b...918e88c)

So looks like several of the Python 3 compatibility fixes regressed performance (at least on Python 2.7.8), but in particular:
https://github.com/linsomniac/python-memcached/commit/45403325e0249ff0f61d6ae449a7daeeb7e852e5

**Comment by methane** [comment]
@edmorley Do you store any objects other than bytes?
This change in 4540332 may affects lot.

```
+import pickle
 import re
-try:
-    import cPickle as pickle
-except ImportError:
-    import pickle
```

**Comment by edmorley** [comment]
Aside from whatever django & it's extensions are doing, the funkiest thing we do iirc is say store zlib compressed json blobs, eg:
https://github.com/mozilla/treeherder/blob/0f3d1b2bcf8700070e7e99892bf1990528811bd0/treeherder/model/derived/jobs.py#L436

**Comment by edmorley** [comment]
Oh and some Django models:
https://github.com/mozilla/treeherder/blob/35fce5772d4ec56621be90d767b5ec8f4beeb937/treeherder/model/models.py#L174

**Comment by edmorley** [comment]
Any news on this? We're contemplating switching to pylibmc due to the perf hit of latest python-memcached versions, particularly since it's pretty worrying that this perf regression wasn't noticed until now. Are benchmarks run as part of development? pylibmc has one checked into their repo for example.
Many thanks :-)

**Comment by linsomniac** [comment]
Have you tried reverting the change @methane mentioned and seeing if that improves the performance?

I appreciate your efforts with identifying and locating this change through bisection.  If you can test the latest release with the pickle change reverted, that would be useful additional information, or if you can provide a latency test so that I can see the impact of that change, I can look into how it impacts it.

Clearly, in your last message, you are disappointed with the regression, and I understand if the pylibmc development process is something you decide warrants a change.  I'd welcome some contributions towards tooling that tests the latency, possibly even reporting of the latency in the ChangeLog for each release?  I don't have time to develop that contribution right now, but perhaps someone who is watching this discussion does.

You may want to consider pinning your upstream dependencies to versions you have tested, and only rolling them forward once you either hit a bug that is fixed in a newer version and/or you have identified that it does not impact your requirements.  I agree that ideally python-memcached would never have latency increase, but the reality is that the community goals for this project may not align with yours, and this is a good example of that: Python 3 support is more important than latency, and we rely on people like you to help identify the latency changes and hopefully to improve upon them.

**Comment by edmorley** [comment]
Thank you for your reply :-)

> Have you tried reverting the change @methane mentioned and seeing if that improves the performance?

Until now I've been testing against our stage instance, since I don't have a reduced testcase for use in our development environment, so it's harder to test than it would be otherwise. I'll see if I can try to do so soon.

> You may want to consider pinning your upstream dependencies to versions you have tested, and only rolling them forward once you either hit a bug that is fixed in a newer version and/or you have identified that it does not impact your requirements.

We do pin versions, this regression was noticed when I was updating the pinned versions to a newer release :-)

> I agree that ideally python-memcached would never have latency increase, but the reality is that the community goals for this project may not align with yours, and this is a good example of that: Python 3 support is more important than latency

I think I might agree if we were talking about a package that did something not related to performance, or if the regression were smaller. But given that the whole point of memcached is that it is a performance enhancer, and that the regression here was a 400% slowdown, I'm afraid we'll have to agree to disagree :-)

> I'd welcome some contributions towards tooling that tests the latency, possibly even reporting of the latency in the ChangeLog for each release?

I'd love to help with this, but am pretty tight for time at the moment. Fingers crossed someone else might be able to chip in.
